// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr36J-B3VpCHQuBe_mumQq8gBEtdx0WOs',
    appId: '1:679237899159:web:8bc1f3a464d61f733e2ad2',
    messagingSenderId: '679237899159',
    projectId: 'baalveda-doctors-b2bae',
    authDomain: 'baalveda-doctors-b2bae.firebaseapp.com',
    storageBucket: 'baalveda-doctors-b2bae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQ9jd0tYGBN2pWUFI_aLIjlLK4KIfRlY',
    appId: '1:679237899159:android:692192aa476015e13e2ad2',
    messagingSenderId: '679237899159',
    projectId: 'baalveda-doctors-b2bae',
    storageBucket: 'baalveda-doctors-b2bae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBzc7xEL2tgeaU8oJVlcfgsw90_1K5A98',
    appId: '1:679237899159:ios:fb082f7d7d2523693e2ad2',
    messagingSenderId: '679237899159',
    projectId: 'baalveda-doctors-b2bae',
    storageBucket: 'baalveda-doctors-b2bae.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBzc7xEL2tgeaU8oJVlcfgsw90_1K5A98',
    appId: '1:679237899159:ios:fb082f7d7d2523693e2ad2',
    messagingSenderId: '679237899159',
    projectId: 'baalveda-doctors-b2bae',
    storageBucket: 'baalveda-doctors-b2bae.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr36J-B3VpCHQuBe_mumQq8gBEtdx0WOs',
    appId: '1:679237899159:web:57f386cf7487d0f33e2ad2',
    messagingSenderId: '679237899159',
    projectId: 'baalveda-doctors-b2bae',
    authDomain: 'baalveda-doctors-b2bae.firebaseapp.com',
    storageBucket: 'baalveda-doctors-b2bae.firebasestorage.app',
  );
}
